### ISSUE TITLE
Issues with selection.trigger / selection.on

### ISSUE THREAD

**Issue by chrtze** [wbkd/d3-extended#2]
We have implemented the d3.on function from [d3-jetpack](https://github.com/gka/d3-jetpack/blob/master/d3-jetpack.js) which is more advanced than the standard selection.on function as you can hand over multiple event names to listen to. 

After adding this new function, our selection.trigger function does not work properly anymore as it relies on the native d3.on function. We are currently looking for an alternative way and have implemented the jQuery.trigger function which is a hotfix for the moment.

At the moment, you can use selection.trigger but it is not possible to hand data over to the event. We are working on a fix for that.

**Comment by moklick** [comment]
fixed https://github.com/wbkd/d3-extended/commit/eb3a0f2f1f60c2b1cff4e78fcb085b4d1ea35ad5
