### ISSUE TITLE
Add position() and fn()

### ISSUE THREAD

**Issue by chrtze** [wbkd/d3-extended#3]
Just two ideas:
- We could add a function for retrieving the position of an svg element (similar to http://stackoverflow.com/questions/13040685/finding-offset-position-of-svg-element)
- We could add a function that enabled you to call a custom function on a selection e.g.: selection.fn(function(d,i) { //do something with d and i })

**Comment by moklick** [comment]
For the `position` function we could use `getBoundingClientRect` what is the difference between `fn` and `each`?

**Comment by chrtze** [comment]
@moklick the problem with ```getBoundingClientRect``` is mentioned in http://stackoverflow.com/a/20407357 : "doesn't account for scroll position or the element's container position relative to the document".

You are right, ```each``` is sufficient for the task i was imagining :+1: .

**Comment by moklick** [comment]
@chrtze Ok.. so I think we need [position](https://api.jquery.com/position/) and [offset](http://api.jquery.com/offset/)

**Comment by chrtze** [comment]
@moklick yep!
