### ISSUE TITLE
Add d3.select().change()

### ISSUE THREAD

**Issue by HarryStevens** [wbkd/d3-extended#4]
Some common jQuery code:
```
$("select").change(function(){
 // do something
});
```
This would be a useful function to add to this library.

**Comment by HarryStevens** [comment]
I suppose there's already
```
d3.select("select").on("change", function(){
  // do something
});
```
But I think the suggestion would still be a slight improvement.

**Comment by g-div** [comment]
Right ! I think we will leave this like it is for now.
